backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "notes"
    label: "Notes"
    folder: "content/notes"
    create: true
    fields:
      - { label: "Subject", name: "subject", widget: "string" }
      - { label: "Class", name: "class", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "homepage"
    label: "Homepage"
    files:
      - label: "Home Page"
        name: "home"
        file: "data/homepage.json"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - {
              label: "Hero Description",
              name: "hero_description",
              widget: "text",
            }
